@startuml
!theme plain
hide empty members
hide stereotypes


skinparam nodesep 60
skinparam ranksep 100
skinparam defaultTextAlignment center
skinparam linetype ortho

' Barevná paleta
skinparam rectangle {
  BackgroundColor #F8FAFC
  BorderColor #334155
  FontColor #0F172A
  RoundCorner 8
}

skinparam rectangle<<primary>> {
  BackgroundColor #EAF2FF
  BorderColor #2B5AA6
}

skinparam rectangle<<core>> {
  BackgroundColor #E8FFF8
  BorderColor #0F766E
}

skinparam rectangle<<secondary>> {
  BackgroundColor #FFF3E0
  BorderColor #C97A10
  FontColor #7C2D12
}


package "(Jádro)" {
  rectangle "Organizace" as org <<core>>
  rectangle "Uživatel" as user <<core>>
}

package "Nábor" {
  rectangle "Katalogová role" as jrole <<primary>>
  rectangle "Pracovní inzerát" as jpost <<primary>>
  rectangle "Uchazeč" as app <<primary>>
  rectangle "Pohovor" as interview <<primary>>
  rectangle "Analýza CV" as ai_cv <<primary>>
}

package "Nástup" {
  rectangle "Šablona" as owf <<secondary>>
  rectangle "Průchod adaptací" as oprog <<secondary>>
}

package " Data" {
  rectangle "Soubor" as doc
  rectangle "Notifikace" as comms
}

' --- STRUKTURÁLNÍ VAZBY ---

' Jádro
org ||-d-o{ user : "sdružuje"


' Nábor
org ||--o{ jrole : "obsahuje"
org ||--o{ jpost : "eviduje"
jpost }o-u-|| jrole : "je přiřazen k"

jpost ||-r-o{ app : "má"
app ||-d-o| ai_cv : "má přiřazenu"
app ||-r-o{ interview : "jde na"
interview }o-u-|| user : "vede"

' Onboarding
org ||--o{ owf : "obsahuje"
oprog }o-l-|| owf : "vzniká z"
user ||-d-o{ oprog : "má evidován"

' Data a Komunikace
app ||-d-o{ doc : "má doložen"
org ||-d-o{ doc 
user ||--o{ comms : "přijímá"

@enduml