#set text(size: 7pt)
#figure(
  table(
    columns: (0.8cm, 0.9cm, 1.1cm, 1.1cm, 1.1cm, 0.8cm, auto),
    inset: 3pt,
    stroke: 0.35pt + gray,

    table.header(
      repeat: true,
      [Scénář], [Účastník], [Dokončeno], [Čas (s)], [Asistence], [Chyby], [Poznámka],
    ),

    [S1], [N01], [ano], [165], [0], [0], [Založení nabídky proběhlo bez asistence; uživatel ocenil předvyplněné číselníky.],
    [S1], [N02], [ano], [175], [0], [0], [Bez zásadních problémů, pouze krátké ověření významu pole pracoviště.],
    [S1], [N03], [ano], [180], [0], [0], [Uživatel se rychle orientoval v rozdělení základních údajů a publikace.],
    [S1], [N04], [ano], [185], [0], [1], [Krátký návrat kvůli kontrole rozsahu úvazku před publikací.],
    [S1], [N05], [ano], [190], [0], [0], [Průchod plynulý, pozitivně hodnocené uložení rozpracované nabídky.],
    [S1], [N06], [ano], [205], [0], [1], [Chybná volba typu pracovního poměru byla opravena bez asistence.],
    [S1], [N07], [ano], [220], [0], [0], [Pomalejší průchod způsobený čtením nápověd a kontrolou povinných polí.],
    [S2], [N01], [ano], [130], [0], [0], [Změna stavu uchazeče byla srozumitelná, cílový stav jednoznačně viditelný.],
    [S2], [N02], [ano], [140], [0], [0], [Bez chyb, uživatel ocenil zobrazení historie uchazeče.],
    [S2], [N03], [ano], [145], [0], [0], [Rychlé zpracování přihlášky, nebyla potřeba asistence.],
    [S2], [N04], [ano], [150], [0], [0], [Stav uchazeče byl změněn správně, komentář doplněn dobrovolně.],
    [S2], [N05], [ano], [155], [1], [1], [Bylo potřeba vysvětlit rozdíl mezi interní poznámkou a zprávou kandidátovi.],
    [S2], [N06], [ano], [165], [0], [0], [Bez problému, uživatel kontroloval navazující notifikaci.],
    [S2], [N07], [ano], [180], [0], [0], [Delší čas kvůli ruční kontrole příloh uchazeče.],
    [S3], [N01], [ano], [135], [0], [0], [Pohovor naplánován rychle, účastníci byli vybráni správně.],
    [S3], [N02], [ano], [150], [0], [0], [Bez chyb, uživatel rozuměl odeslání pozvánek.],
    [S3], [N03], [ano], [160], [0], [0], [Uživatel si ověřoval, zda pozvánka odchází kandidátovi i interním účastníkům.],
    [S3], [N04], [ano], [165], [0], [0], [Scénář dokončen plynule.],
    [S3], [N05], [ano], [175], [1], [1], [Bylo nutné dovysvětlit výběr účastníků pohovoru.],
    [S3], [N06], [ano], [190], [0], [0], [Uživatel provedl dodatečnou kontrolu data a času.],
    [S3], [N07], [ano], [205], [0], [0], [Delší průchod bez chyby, uživatel postupoval opatrně.],
    [S4], [N01], [ano], [120], [0], [0], [Převod byl dokončen, uživatel měl předchozí zkušenost s procesem.],
    [S4], [N02], [ano], [135], [0], [0], [Bez asistence, uživatel správně navázal vstupní agendu.],
    [S4], [N03], [ano], [145], [0], [0], [Scénář dokončen, ale uživatel si ověřoval význam finálního stavu.],
    [S4], [N04], [ano], [150], [1], [1], [Bylo potřeba vysvětlit rozdíl mezi změnou stavu a spuštěním vstupní agendy.],
    [S4], [N05], [ano], [165], [0], [0], [Převod dokončen, uživatel ocenil návaznost na úkoly.],
    [S4], [N06], [ano], [180], [0], [0], [Pomalejší průchod kvůli kontrole údajů uchazeče.],
    [S4], [N07], [ne], [--], [0], [1], [Uživatel skončil u změny stavu uchazeče a nepokračoval ke spuštění vstupní agendy.],
    [S4], [P01], [ano], [205], [0], [0], [Scénář dokončen po kontrole personálních údajů.],
    [S4], [P02], [ne], [--], [1], [1], [Uživatelka si nebyla jistá, zda již pracuje s uchazečem nebo budoucím zaměstnancem.],
    [S5], [U01], [ano], [300], [0], [0], [Úkol vstupní agendy byl srozumitelný, dokument se podařilo nahrát napoprvé.],
    [S5], [U02], [ano], [330], [0], [1], [Uživatel se krátce vracel kvůli kontrole typu nahrávaného dokumentu.],
    [S6], [V01], [ano], [170], [0], [0], [Report byl dohledán rychle, vedoucí ocenil souhrnný pohled na průchodnost.],
    [S7], [N01], [ano], [75], [0], [0], [Notifikace byla rozpoznána a vyřízena bez zaváhání.],
    [S7], [N02], [ano], [82], [0], [0], [Bez problému.],
    [S7], [N03], [ano], [90], [0], [0], [Uživatel rychle přešel z notifikace na detail úkolu.],
    [S7], [N04], [ano], [95], [0], [0], [Postup plynulý.],
    [S7], [N05], [ano], [98], [0], [0], [Notifikace byla srozumitelná.],
    [S7], [N06], [ano], [100], [0], [0], [Mediánový průchod bez asistence.],
    [S7], [N07], [ano], [105], [0], [1], [Uživatel nejprve otevřel seznam notifikací místo přímo navázaného úkolu.],
    [S7], [P01], [ano], [110], [0], [0], [Bez problému.],
    [S7], [P02], [ano], [115], [0], [0], [Uživatelka ocenila jasné oddělení přečtených a nepřečtených oznámení.],
    [S7], [U01], [ano], [125], [0], [0], [Uživatel našel navazující úkol z notifikace.],
    [S7], [U02], [ano], [140], [0], [0], [Pomalejší orientace, ale bez asistence.],
  ),
  caption: [Detailní anonymizovaný záznam pilotního uživatelského ověření],
) <tab:user-test-raw-data>
