-- Job embeddings cache table for async job matching
-- Stores precomputed embeddings for job postings to enable fast matching
-- Embeddings are generated by Go worker via RabbitMQ

CREATE TABLE job_embeddings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id UUID NOT NULL REFERENCES job_postings(id) ON DELETE CASCADE,

    -- Content hash for cache invalidation (SHA256 of title + description + requirements)
    content_hash VARCHAR(64) NOT NULL,

    -- Embedding vector (nomic-embed-text = 768 dimensions)
    embedding vector(768),

    -- Status tracking
    status VARCHAR(20) DEFAULT 'pending'
        CHECK (status IN ('pending', 'processing', 'completed', 'failed')),
    error_message TEXT,

    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE,
    processed_at TIMESTAMP WITH TIME ZONE,
    failed_at TIMESTAMP WITH TIME ZONE,

    -- Processing metadata
    model_used VARCHAR(100) DEFAULT 'nomic-embed-text',
    processing_time_ms INTEGER,

    -- One embedding per job (upsert on reprocessing)
    CONSTRAINT uq_job_embedding UNIQUE (job_id)
);

-- Indexes for efficient queries
CREATE INDEX idx_job_embeddings_status ON job_embeddings(status);
CREATE INDEX idx_job_embeddings_job_id ON job_embeddings(job_id);


CREATE INDEX idx_job_embeddings_vec 
ON job_embeddings 
USING hnsw (embedding vector_cosine_ops);

-- Rollback instructions:
-- DROP TABLE job_embeddings;
